import type { AlarmControlPanelEntity as AlarmControlPanelEntityBase } from "../autogenerated-types-by-domain";

export type AlarmPanelCardConfigState = "arm_away" | "arm_home" | "arm_night" | "arm_vacation" | "arm_custom_bypass";

export type AlarmMode =
  | "armed_home"
  | "armed_away"
  | "armed_night"
  | "armed_vacation"
  | "armed_custom_bypass"
  | "disarmed"
  | "triggered"
  | "arming"
  | "pending";

export interface AlarmControlPanelEntity extends AlarmControlPanelEntityBase {
  state: AlarmMode;
}
