import { HassEntityAttributeBase } from "home-assistant-js-websocket";

import type { VacuumEntity as VacuumEntityBase } from "../autogenerated-types-by-domain";

export type VacuumEntityState =
  | "cleaning"
  | "docked"
  | "idle"
  | "paused"
  | "returning"
  | "error"
  | "unknown"
  | string; // for other states

export interface VacuumEntityAttributes extends HassEntityAttributeBase {
  status?: VacuumEntityState;
  state?: VacuumEntityState;
  fan_speed?: string;
  fan_speed_list?: string[];
  battery_level?: number;
  battery_icon?: string;
}

export interface VacuumCardShortcut {
  name?: string;
  icon?: string;
  service?: string;
  service_data?: Record<string, unknown>;
}

export interface VacuumCardStat {
  entity_id?: string;
  attribute?: string;
  value_template?: string;
  unit?: string;
  subtitle?: string;
}

export interface VacuumCardAction {
  service: string;
  service_data?: Record<string, unknown>;
}

export interface VacuumCardConfig {
  entity: string;
  map: string;
  map_refresh: number;
  image: string;
  show_name: boolean;
  show_status: boolean;
  show_toolbar: boolean;
  compact_view: boolean;
  stats: Record<string, VacuumCardStat[]>;
  actions: Record<string, VacuumCardAction>;
  shortcuts: VacuumCardShortcut[];
}

export interface VacuumEntity extends VacuumEntityBase {
  attributes: VacuumEntityAttributes;
  state: VacuumEntityState;
}
