import { HassEntityAttributeBase } from "home-assistant-js-websocket";

import type { VacuumEntity as VacuumEntityBase } from "../autogenerated-types-by-domain";

export type VacuumEntityState = "on" | "off" | "cleaning" | "docked" | "idle" | "paused" | "returning" | "error" | "unknown";

export interface VacuumEntityAttributes extends HassEntityAttributeBase {
  status?: VacuumEntityState;
  state?: VacuumEntityState;
  fan_speed?: string;
  fan_speed_list?: string[];
  battery_level?: number;
  battery_icon?: string;
}

export interface VacuumEntity extends VacuumEntityBase {
  attributes: VacuumEntityAttributes;
  state: VacuumEntityState;
}
